" ------------------------------------------------------------------------
" .VIMRC
" by nwj
" ------------------------------------------------------------------------


" PATHOGEN
" ------------------------------------------------------------------------
" must come first. comment out if not using plugins
call pathogen#infect()
call pathogen#helptags()


" BASIC SETTINGS
" ------------------------------------------------------------------------
set nocompatible
set hidden
set number
set ruler
set history=1000
set backspace=indent,eol,start
set encoding=utf-8


" COLOR
" ------------------------------------------------------------------------
colorscheme zenburn


" TABS, INDENTS, WRAPPING
" ------------------------------------------------------------------------
set smartindent
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set shiftround
set nowrap

" WHITESPACE
" ------------------------------------------------------------------------
set list
set listchars=""
set listchars=tab:\ \
set listchars+=trail:.
set listchars+=extends:>
set listchars+=precedes:<


" SEARCH
" ------------------------------------------------------------------------
set ignorecase
set smartcase
set incsearch
set hlsearch
set showmatch


" BACKUPS
" ------------------------------------------------------------------------
set nobackup
set nowb
set noswapfile


" FILETYPE DETECTION
" ------------------------------------------------------------------------
filetype plugin indent on
syntax enable


" BASIC KEY BINDINGS
" ------------------------------------------------------------------------
" command mode without pressing shift
nnoremap ; :
vnoremap ; :

" make Y behave similar to C and D
nnoremap Y y$

" sets the leader key
let mapleader = ","

" shortcut to toggle search highlighting
nmap <leader>h :set hlsearch! hlsearch? <CR>

" expand file location of current buffer
cnoremap %% <C-R>=expand('%:h').'/'<cr>
map <leader>e :e %%

" get write permission when you forget sudo
cmap w!! w !sudo tee %


" PLUGINS
" ------------------------------------------------------------------------
" ctrl-p keybinding
let g:ctrlp_map = "<c-p>"
let g:ctrlp_show_hidden = 1
let g:ctrlp_use_caching = 1
let g:ctrlp_clear_cache_on_exit = 0

" nerd commenter keybinding
map <leader>/ <plug>NERDCommenterToggle

" nerd tree keybinding
map <leader>n :NERDTreeToggle <CR>

" LANGUAGE SPECIFIC SETTINGS
" ------------------------------------------------------------------------
autocmd BufNewFile,BufRead *.rb set shiftwidth=2
autocmd BufNewFile,BufRead *.rb set tabstop=2
autocmd BufNewFile,BufRead *.rb set softtabstop=2
autocmd BufNewFile,BufRead *.rb set expandtab
