# ----------------------------------------------------------------------------------------------------------
# ZSH CONFIGURATION | Author: nwj
# ----------------------------------------------------------------------------------------------------------

# OH MY ZSH CONFIGURATION
# ----------------------------------------------------------------------------------------------------------
export ZSH=$HOME/.oh-my-zsh

# Set oh-my-zsh theme
ZSH_THEME="af-magic"

# Disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

source $ZSH/oh-my-zsh.sh

# GENERAL PATH MODIFICATIONS
# ----------------------------------------------------------------------------------------------------------
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# LANGUAGE-SPECIFIC SETTINGS
# ----------------------------------------------------------------------------------------------------------
# Setup rbenv if it exists
if [ -d $HOME/.rbenv/bin ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
fi
if [[ $+commands[rbenv] != 0 ]]; then
  eval "$(rbenv init -)"
fi

# OTHER SETTINGS
# ----------------------------------------------------------------------------------------------------------
# Enable vi key bindings (rather than Emacs-esque key bindings)
bindkey -v
bindkey '^R' 'history-incremental-search-backward'
bindkey -M vicmd '^R' 'history-incremental-search-backward'

# Enable fzf keybindings
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Make FZF use fd. This is good because fd respects .gitignore in its results.
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Enable zmv
autoload zmv
